### PR TITLE
Update US Endpoint

### PR DESCRIPTION
**Pull request by tanji**
The US endpoint Domain Name has changed. Reflecting this change in the endpoint mapping list.

By making a contribution to this project, I certify that:

The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or
The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source License and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or
The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.
The contribution is made free of any other party's intellectual property claims or rights.
I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

Signed-off-by: Guillaume Lefranc <guillaume@signal18.io>

### CODE REVIEW

**Comment by rbeuque74** [comment]
Build is currently failed (see #68), in the meantime, I will merge this pull-request which is not responsible of broken build.

**Comment by tanji** [comment]
I already did this in the PR, is it insufficient? I don't think I can edit my commit without closing this PR

**Comment by rbeuque74** [comment]
The "legal" text is not mandatory, you just need to sign-off the commit using the flag ```-s``` while commiting.

You can edit your commit without closing the pull-request.

```bash
git commit -a --amend --no-edit -s
git push origin patch-1 -f
```

While you are modifying your commit, could you modify the URL in the README.rst for api.ovhcloud.com -> api.us.ovhcloud.com ? If you can't do it, I will do it in another commit, don't worry ;)

**Comment by rbeuque74** [comment]
Merged as of #70

**Pull request closed without merging**
