### PR TITLE
Add InvalidKey exception on http code 403

### PR DESCRIPTION
**Pull request by bewiwi**

### CODE REVIEW

**Comment by yadutaf** [comment]
LGTM.

**Comment by yadutaf** [comment]
Before I can merge, can you sign your commit ? A command like ``git commit -s --amend && git push -f`` should do the trick. Thanks.

**Comment by yadutaf** [comment]
Ok, better. @gierschv Good to go ?

**Comment by gierschv** [comment]
Ok, LGTM.

**Pull request merged**
