### PR TITLE
Added doc for passing parameters

### PR DESCRIPTION
**Pull request by alkivi-sas**

### CODE REVIEW

**Comment by yadutaf** [comment]
Thanks for this addition! Before I can merge, can you apply your changes to ``docs/index.rst`` too and squash + sign your commits?

For the squash, a command like:
```
git remote add upstream https://github.com/ovh/python-ovh.git
git rebase -i upstream/master
```

To sign your commits: ``git commit --amend -s``

**Comment by alkivi-sas** [comment]
Should be better now

**Comment by yadutaf** [comment]
Looks good to me. Thanks. @VincentCasse Good to merge?

**Comment by VincentCasse** [comment]
Seems good for me.
@yadutaf  I merge, you release?

**Pull request merged**
