### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by chtitux**

### CODE REVIEW

**Comment by yadutaf** [comment]
Hi @chtitux !

Thanks for the typo fix. Can you sign your commit ? ``git commit --amend -s --no-edit && git push -f`` should do the job.

**Comment by gierschv** [comment]
@chtitux By the way, "for more information" without "s".

**Comment by chtitux** [comment]
Too bad github can't do that via its online edotir :(
I'll try to amend my commi today.

**Comment by chtitux** [comment]
@yadutaf done for amending. I've fixed other typos, including the one in #2

**Comment by yadutaf** [comment]
Merged. Thanks!

**Pull request merged**
