### PR TITLE
Drop conflicting d2to1 dependency

### PR DESCRIPTION
**Pull request by yadutaf**
Some user are experiencing difficulties using python-ovh on their system because of conflicting d2to1 version. While a good practice is to use virtualenvs, which are not affected by this bug, this is not always practical.

Given this, we have multiple options:
- upgrade d2to1 requirements / accept multiple versions --> would only postpone the problem
- vendor d2to1
- drop d2to1

As d2to1 is not a crucial library like request is, the overhead of vendoring and maintaining it is not worth. Hence the proposition to drop it altogether.

### CODE REVIEW

**Comment by yadutaf** [comment]
This supersedes #27

**Comment by hasB4K** [comment]
Hello,

So I have tested the installation on this branch, it works perfectly. The pull request #27 is now useless.
Thanks for your work!

Regards,

-- 
Mathis 'hasB4K' FELARDOS

**Comment by NicolasLM** [comment]
Good, you could also remove the list of packages and replace it by [find_packages](https://pythonhosted.org/setuptools/setuptools.html#using-find-packages).

**Comment by yadutaf** [comment]
Thanks for the tip. Applied :)

**Comment by yadutaf** [comment]
Thanks for the feedback @hasB4K. Will likely get merged later today.

**Comment by VincentCasse** [comment]
LGTM

**Pull request merged**
